BUBBLE_TYPE_NORMAL = 0
BUBBLE_TYPE_PUBLIC = 1
BUBBLE_TYPE_SECRET = 2

BUBBLE_TYPES = set([BUBBLE_TYPE_NORMAL, BUBBLE_TYPE_PUBLIC])

# Bubble roles
BUBBLE_ROLE_INVITEE = 0
BUBBLE_ROLE_APPLICANT = 1
BUBBLE_ROLE_MEMBER = 2
BUBBLE_ROLE_ADMIN = 3

BUBBLE_ROLES = set([BUBBLE_ROLE_INVITEE, BUBBLE_ROLE_APPLICANT, BUBBLE_ROLE_MEMBER, BUBBLE_ROLE_ADMIN])

# Post types
POST_TYPE_DISCUSSION = 0
POST_TYPE_EVENT = 1
POST_TYPE_FILE = 2

POST_TYPES = set([POST_TYPE_DISCUSSION, POST_TYPE_EVENT, POST_TYPE_FILE])

# Bubble flag types
BUBBLE_FLAG_PENDING = 0
BUBBLE_FLAG_REVIEWED = 1
BUBBLE_FLAG_DELETED = 2

# Video services
POST_VIDEO_SERVICE_YOUTUBE = 0

POST_VIDEO_SERVICE_TYPES = set([POST_VIDEO_SERVICE_YOUTUBE])

# Bubble application status
APPLICATION_STATUS_PENDING = 0
APPLICATION_STATUS_REJECTED = 1
APPLICATION_STATUS_APPROVED = 2

# Bubble flag types
BUBBLE_FLAG_PENDING = 0
BUBBLE_FLAG_REVIEWED = 1
BUBBLE_FLAG_DELETED = 2

BUBBLE_COLORS = (
    ('red-color','Red'),
    ('orange-color','Orange'),
    ('yellow-color','Yellow'),
    ('green-color','Green'),
    ('blue-color','Blue'),
    ('violet-color','Violet'),
)